// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomain = "domains"

// Domain mapped from table <domains>
type Domain struct {
	CreatedAt time.Time `gorm:"column:created_at;not null;default:timezone('utc'::text, CURRENT_TIMESTAMP)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:timezone('utc'::text, CURRENT_TIMESTAMP)" json:"updated_at"`
	OwnerID   string    `gorm:"column:owner_id" json:"owner_id"`
	URL       string    `gorm:"column:url;not null" json:"url" validate:"domain_url"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Gravatar  string    `gorm:"column:gravatar;not null" json:"gravatar"`
	Bulletin  string    `gorm:"column:bulletin;not null" json:"bulletin"`
	Hidden    bool      `gorm:"column:hidden;not null" json:"hidden"`
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Group_    string    `gorm:"column:group;not null;default:''::character varying" json:"group"`
	Tag       string    `gorm:"column:tag" json:"tag"`
}

// TableName Domain's table name
func (*Domain) TableName() string {
	return TableNameDomain
}
